server:
  port: 6868

eureka:
  client:
    #是否将自己注册到Eureka服务中，本身就是所有无需注册
    register-with-eureka: false
    #是否从Eureka中获取注册信息
    fetch-registry: false
    #Eureka客户端与Eureka服务端进行交互的地址
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
#  instance:
#    ip-address: 127.0.0.1

#spring:
#  security:
#    user:
#      name: jun
#      password: jun123

# https://blog.csdn.net/qq_35221138/article/details/81016171#commentsedit
