server:
  port: 8081

spring:
  application:
    name: jun-microservice-item

eureka:
  client:
    #是否将自己注册到Eureka服务中，默认为true
    registerWithEureka: true
    #是否从Eureka中获取注册信息，默认为true
    fetchRegistry: true
    #Eureka客户端与Eureka服务端进行交互的地址
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
#      defaultZone: http://jun:jun123@127.0.0.1:6868/eureka/
  instance:
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true