server:
  port: 6677

spring:
  application:
    name: jun-microservice-api-gateway

zuul:
  routes:
    item-serivce:
      path: /item-service/**
      # url: http://127.0.0.1:8081
      # 指定Eureka 注册中心的服务 id
      serviceId: jun-microservice-item

eureka:
  client:
    # 是否将自己注册到Eureka服务中，默认为true
    register-with-eureka: true
    # 是否从Eureka中获取注册信息，默认为true
    fetch-registry: true
    # Eureka 客户端与 Eureka 服务端 进行交互的地址
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    # 将自己的IP地址注册到Eureka服务中
    prefer-ip-address: true